//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoTelefono
    {
        public int id { get; set; }
        public string numero { get; set; }
        public int contactoID { get; set; }
    
        public virtual Contacto Contacto { get; set; }
    }
}
